# Simple Event Receiver Workflow
# This workflow demonstrates how to receive events via triggers
name: simple-receiver
kind: module
description: Simple workflow that receives and processes events
tags: event,receiver,trigger,example
hidden: true

triggers:
  # Trigger on new asset discovery events
  - name: on-new-asset
    on: event
    event:
      topic: "discovery.asset"
      filters:
        - "event.source == 'simple-emitter'"
        - "event.data_type == 'subdomain'"
      dedupe_key: "{{event.source}}-{{event.data}}"
      dedupe_window: 10s
    input:
      target: event_data.value
    enabled: true

  # this is to disable the workflow to run from CLI
  - name: manual-trigger
    on: manual
    enabled: false

params:
  - name: target
    required: true

steps:
  - name: log-received
    type: function
    functions:
      - 'print_blue("Received event for target: {{target}}")'

  - name: process-asset
    type: bash
    command: |
      echo "Processing asset: {{target}}"
      echo "{{target}}" >> {{Output}}/processed-assets.txt

  - name: log-complete
    type: function
    functions:
      - 'print_green("Processed: {{target}}")'

  - name: verify-vars
    type: bash
    commands:
      - 'echo "Target={{Target}}"'
      - 'echo "TargetSpace={{TargetSpace}}"'
      - 'echo "Output={{Output}}"'
      - 'echo "RunUUID={{RunUUID}}"'
      - 'echo "asset_type={{asset_type}}"'
      - 'echo "source={{source}}"'
      - 'echo "description={{description}}"'
